import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import CategoryBar from "@/components/shared/CategoryBar/CategoryBar";
import NewsLetter from "@/components/shared/NewsLetter/NewsLetter";

const kanit = Kanit({
  weight: ["400", "700"],
  variable: "--font-kanit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.variable}>
        <div className="shadow-2xl">
          <Navbar />
          <CategoryBar />
        </div>
        <div className="bg-gray-50 py-8">{children}</div>
        <NewsLetter />
        <Footer />
      </body>
    </html>
  );
}
