import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import CategoryBar from "@/components/shared/CategoryBar/CategoryBar";
import NewsLetter from "@/components/shared/NewsLetter/NewsLetter";
import localFont from "next/font/local";

const kanit = Kanit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const googleSans = localFont({
  src: [
    {
      path: "../../public/fonts/GoogleSans/GoogleSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/GoogleSans/GoogleSans-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/GoogleSans/GoogleSans-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/GoogleSans/GoogleSans-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-google-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={googleSans.className}>
        <div className="shadow-2xl">
          <Navbar />
          <CategoryBar />
        </div>
        <div className="bg-gray-50 py-4 px-2 sm:px-0">{children}</div>
        <NewsLetter />
        <Footer />
      </body>
    </html>
  );
}
